[package]
name = "steam-session-proto"
version = "0.1.0"
authors = ["Julia"]
edition = "2018"
description = "Protobuf structs used for Steam sessions"
license = "MIT"

[dependencies]
protobuf = "3.4.0"

[build-dependencies]
protobuf = "3.4.0"
protobuf-codegen = "3.4.0"